### ISSUE TITLE
Support multiple pi garage

### ISSUE THREAD

**Issue by michaelgambold** [michaelgambold/pi-garage#97]
It might be possible that users want access to multiple pi garage instances (with different configurations).

Should look at converting single saved fields into an array of object configs.

Will probably need a Config record to keep track of current/last selected index

**Comment by michaelgambold** [comment]
Accepted, slated for 1.8.0 release (target by end of April 2023).

To accomplish this it only needs to be in the mobile app and not the backend service so shouldn't be a breaking change to functionality (we just need a migration path).

Items to complete:

- [ ] Support get/set multiple configs into local storage (#185)
- [ ] Have migration path for data migration (needs to happen on app start after upgrading) (#185)
- [ ] Create UI element for config selection (#185)
- [ ] Add ui element to menu widget (#185)
- [ ] Change Global settings to Configs to show list of configs
- [ ] Create edit config screen
- [ ] Add routing for config list/config edit screens
- [ ] Update screenshots for new menus
- [ ] Update documentation for multiple configs

**Comment by michaelgambold** [comment]
Updating this note. The only task remaining it to update this in the documentation. This will probably be done at the same time as the documentation is updated for version 2 and redis requirement.

**Comment by michaelgambold** [comment]
Closing this as documentation has been done and can be seen here.

https://michaelgambold.github.io/pi-garage/#/?id=multiple-configurations
